//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magensa.EMV.Services
{
    using global::EMV.ServiceFactory;
    using System;
    using System.Runtime.Serialization;
    using System.Xml;
    using System.Xml.Linq;
    using System.Xml.Serialization;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasicTransactionRequestInfo", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.EMV.Services.GetClockSetCommandRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.EMV.Services.GetEMVCommandsRequest))]
    [Serializable]
    public partial class BasicTransactionRequestInfo : object
    {
        
        private Magensa.EMV.Services.Authentication AuthenticationField;
        
        private string BillingLabelField;
        
        private string CustomerTransactionIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        
        public Magensa.EMV.Services.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public string BillingLabel
        {
            get
            {
                return this.BillingLabelField;
            }
            set
            {
                this.BillingLabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authentication", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    [Serializable]
    public partial class Authentication : object
    {
        
        private string CustomerCodeField;
        
        private string PasswordField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        
        public string CustomerCode
        {
            get
            {
                return this.CustomerCodeField;
            }
            set
            {
                this.CustomerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetClockSetCommandRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    [Serializable]
    public partial class GetClockSetCommandRequest : Magensa.EMV.Services.BasicTransactionRequestInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private string DateYYYYMMDDField;
        
        private string DeviceTypeField;
        
        private string KSNField;
        
        private string KeyNameField;
        
        private string SerialNumberField;
        
        private string TimeHHMMSSField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        
        public string DateYYYYMMDD
        {
            get
            {
                return this.DateYYYYMMDDField;
            }
            set
            {
                this.DateYYYYMMDDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public string DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        
        public string KeyName
        {
            get
            {
                return this.KeyNameField;
            }
            set
            {
                this.KeyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        
        public string SerialNumber
        {
            get
            {
                return this.SerialNumberField;
            }
            set
            {
                this.SerialNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        
        public string TimeHHMMSS
        {
            get
            {
                return this.TimeHHMMSSField;
            }
            set
            {
                this.TimeHHMMSSField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetEMVCommandsRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    [Serializable]
    public partial class GetEMVCommandsRequest : Magensa.EMV.Services.BasicTransactionRequestInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private string DeviceTypeField;
        
        private string EMVCommandTypeField;
        
        private string KSNField;
        
        private string KeyNameField;
        
        private string SerialNumberField;
        
        private string XMLStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public string DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public string EMVCommandType
        {
            get
            {
                return this.EMVCommandTypeField;
            }
            set
            {
                this.EMVCommandTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        
        public string KeyName
        {
            get
            {
                return this.KeyNameField;
            }
            set
            {
                this.KeyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        
        public string SerialNumber
        {
            get
            {
                return this.SerialNumberField;
            }
            set
            {
                this.SerialNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string XMLString
        {
            get
            {
                return this.XMLStringField;
            }
            set
            {
                this.XMLStringField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasicTransactionResponseInfo", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.EMV.Services.GetClockSetCommandResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.EMV.Services.GetEMVCommandsResponse))]
    [Serializable]
    public partial class BasicTransactionResponseInfo : object
    {
        
        private string CustomerTransactionIdField;
        
        private string MagTranIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public string CustomerTransactionId
        {
            get
            {
                return this.CustomerTransactionIdField;
            }
            set
            {
                this.CustomerTransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public string MagTranId
        {
            get
            {
                return this.MagTranIdField;
            }
            set
            {
                this.MagTranIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetClockSetCommandResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    [Serializable]
    public partial class GetClockSetCommandResponse : Magensa.EMV.Services.BasicTransactionResponseInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputDataField;
        
        private Magensa.EMV.Services.Command CommandField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputData
        {
            get
            {
                return this.AdditionalOutputDataField;
            }
            set
            {
                this.AdditionalOutputDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public Magensa.EMV.Services.Command Command
        {
            get
            {
                return this.CommandField;
            }
            set
            {
                this.CommandField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetEMVCommandsResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    [Serializable]
    public partial class GetEMVCommandsResponse : Magensa.EMV.Services.BasicTransactionResponseInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputDataField;
        
        private Magensa.EMV.Services.Command[] CommandsField;
        
        private Magensa.EMV.Services.Command[] PostloadCommandsField;
        
        private Magensa.EMV.Services.Command[] PreloadCommandsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputData
        {
            get
            {
                return this.AdditionalOutputDataField;
            }
            set
            {
                this.AdditionalOutputDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public Magensa.EMV.Services.Command[] Commands
        {
            get
            {
                return this.CommandsField;
            }
            set
            {
                this.CommandsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public Magensa.EMV.Services.Command[] PostloadCommands
        {
            get
            {
                return this.PostloadCommandsField;
            }
            set
            {
                this.PostloadCommandsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public Magensa.EMV.Services.Command[] PreloadCommands
        {
            get
            {
                return this.PreloadCommandsField;
            }
            set
            {
                this.PreloadCommandsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Command", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    [Serializable]
    public partial class Command : object
    {
        
        private int CommandTypeField;
        
        private string DescriptionField;
        
        private string ExecutionTypeEnumField;
        
        private int IDField;
        
        private string NameField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public int CommandType
        {
            get
            {
                return this.CommandTypeField;
            }
            set
            {
                this.CommandTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public string ExecutionTypeEnum
        {
            get
            {
                return this.ExecutionTypeEnumField;
            }
            set
            {
                this.ExecutionTypeEnumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.magensa.net/RemoteServices/v2/", ConfigurationName="Magensa.EMV.Services.IEMV")]
    public interface IEMV
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IEMV/GetEMVCommands", ReplyAction="http://www.magensa.net/RemoteServices/v2/IEMV/GetEMVCommandsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/IEMV/GetEMVCommandsFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        System.Threading.Tasks.Task<Magensa.EMV.Services.GetEMVCommandsResponse> GetEMVCommandsAsync(Magensa.EMV.Services.GetEMVCommandsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IEMV/GetClockSetCommand", ReplyAction="http://www.magensa.net/RemoteServices/v2/IEMV/GetClockSetCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/IEMV/GetClockSetCommandFaultExceptionFau" +
            "lt", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        System.Threading.Tasks.Task<Magensa.EMV.Services.GetClockSetCommandResponse> GetClockSetCommandAsync(Magensa.EMV.Services.GetClockSetCommandRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IEMVChannel : Magensa.EMV.Services.IEMV, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class EMVClient : System.ServiceModel.ClientBase<Magensa.EMV.Services.IEMV>, Magensa.EMV.Services.IEMV
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EMVClient() : 
                base(EMVClient.GetDefaultBinding(), EMVClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpsBinding_IEMV.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EMVClient(EndpointConfiguration endpointConfiguration) : 
                base(EMVClient.GetBindingForEndpoint(endpointConfiguration), EMVClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EMVClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EMVClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EMVClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EMVClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EMVClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Magensa.EMV.Services.GetEMVCommandsResponse> GetEMVCommandsAsync(Magensa.EMV.Services.GetEMVCommandsRequest request)
        {
            return base.Channel.GetEMVCommandsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.EMV.Services.GetClockSetCommandResponse> GetClockSetCommandAsync(Magensa.EMV.Services.GetClockSetCommandRequest request)
        {
            return base.Channel.GetClockSetCommandAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IEMV))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IEMV))
            {
                return new System.ServiceModel.EndpointAddress("https://devgw.magensa.dev/RemoteServicesV2/EMV.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EMVClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpsBinding_IEMV);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EMVClient.GetEndpointAddress(EndpointConfiguration.BasicHttpsBinding_IEMV);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpsBinding_IEMV,
        }
    }
}
