//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magensa.PPSCRAv2.Services
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasicTransactionRequestInfo", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.PPSCRAv2.Services.GetPPKeyLoadCommandRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.PPSCRAv2.Services.GetAmkKeyLoadCommandRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.PPSCRAv2.Services.GetCertLoadCommandRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.PPSCRAv2.Services.GetLoadConfigCommandRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.PPSCRAv2.Services.GetCommandListByDeviceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.PPSCRAv2.Services.GetDeviceAuthCommandRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.PPSCRAv2.Services.GetPreActivateCommandRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.PPSCRAv2.Services.GetEnableSREDCommandRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.PPSCRAv2.Services.GetKeyListRequest))]
    public partial class BasicTransactionRequestInfo : object
    {
        
        private Magensa.PPSCRAv2.Services.Authentication AuthenticationField;
        
        private string BillingLabelField;
        
        private string CustomerTransactionIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.PPSCRAv2.Services.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingLabel
        {
            get
            {
                return this.BillingLabelField;
            }
            set
            {
                this.BillingLabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authentication", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class Authentication : object
    {
        
        private string CustomerCodeField;
        
        private string PasswordField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomerCode
        {
            get
            {
                return this.CustomerCodeField;
            }
            set
            {
                this.CustomerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPPKeyLoadCommandRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetPPKeyLoadCommandRequest : Magensa.PPSCRAv2.Services.BasicTransactionRequestInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private string ChallengeField;
        
        private string DeviceCertField;
        
        private string DeviceTypeField;
        
        private string KSIField;
        
        private string KSNField;
        
        private string KeyTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Challenge
        {
            get
            {
                return this.ChallengeField;
            }
            set
            {
                this.ChallengeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeviceCert
        {
            get
            {
                return this.DeviceCertField;
            }
            set
            {
                this.DeviceCertField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KSI
        {
            get
            {
                return this.KSIField;
            }
            set
            {
                this.KSIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KeyType
        {
            get
            {
                return this.KeyTypeField;
            }
            set
            {
                this.KeyTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAmkKeyLoadCommandRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetAmkKeyLoadCommandRequest : Magensa.PPSCRAv2.Services.BasicTransactionRequestInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private string ChallengeField;
        
        private string DeviceCertField;
        
        private string DeviceSNField;
        
        private string DeviceTypeField;
        
        private string KSIField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Challenge
        {
            get
            {
                return this.ChallengeField;
            }
            set
            {
                this.ChallengeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeviceCert
        {
            get
            {
                return this.DeviceCertField;
            }
            set
            {
                this.DeviceCertField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeviceSN
        {
            get
            {
                return this.DeviceSNField;
            }
            set
            {
                this.DeviceSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KSI
        {
            get
            {
                return this.KSIField;
            }
            set
            {
                this.KSIField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCertLoadCommandRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetCertLoadCommandRequest : Magensa.PPSCRAv2.Services.BasicTransactionRequestInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private string ChallengeField;
        
        private string DeviceTypeField;
        
        private string KSNField;
        
        private string KeyTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Challenge
        {
            get
            {
                return this.ChallengeField;
            }
            set
            {
                this.ChallengeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KeyType
        {
            get
            {
                return this.KeyTypeField;
            }
            set
            {
                this.KeyTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLoadConfigCommandRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetLoadConfigCommandRequest : Magensa.PPSCRAv2.Services.BasicTransactionRequestInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private string ChallengeField;
        
        private Magensa.PPSCRAv2.Services.DeviceConfigCommand[] ConfigCommandsField;
        
        private string DeviceTypeField;
        
        private string ExistingConfigField;
        
        private string KSNField;
        
        private string KeyTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Challenge
        {
            get
            {
                return this.ChallengeField;
            }
            set
            {
                this.ChallengeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.PPSCRAv2.Services.DeviceConfigCommand[] ConfigCommands
        {
            get
            {
                return this.ConfigCommandsField;
            }
            set
            {
                this.ConfigCommandsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ExistingConfig
        {
            get
            {
                return this.ExistingConfigField;
            }
            set
            {
                this.ExistingConfigField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KeyType
        {
            get
            {
                return this.KeyTypeField;
            }
            set
            {
                this.KeyTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCommandListByDeviceRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetCommandListByDeviceRequest : Magensa.PPSCRAv2.Services.BasicTransactionRequestInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private string DeviceTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeviceAuthCommandRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetDeviceAuthCommandRequest : Magensa.PPSCRAv2.Services.BasicTransactionRequestInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private string ChallengeField;
        
        private string DeviceCertField;
        
        private string DeviceTypeField;
        
        private string KeyTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Challenge
        {
            get
            {
                return this.ChallengeField;
            }
            set
            {
                this.ChallengeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeviceCert
        {
            get
            {
                return this.DeviceCertField;
            }
            set
            {
                this.DeviceCertField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KeyType
        {
            get
            {
                return this.KeyTypeField;
            }
            set
            {
                this.KeyTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPreActivateCommandRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetPreActivateCommandRequest : Magensa.PPSCRAv2.Services.BasicTransactionRequestInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private string ChallengeField;
        
        private string DeviceTypeField;
        
        private string KSNField;
        
        private string KeyTypeField;
        
        private string OrderIDField;
        
        private string TechIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Challenge
        {
            get
            {
                return this.ChallengeField;
            }
            set
            {
                this.ChallengeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KeyType
        {
            get
            {
                return this.KeyTypeField;
            }
            set
            {
                this.KeyTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TechID
        {
            get
            {
                return this.TechIDField;
            }
            set
            {
                this.TechIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetEnableSREDCommandRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetEnableSREDCommandRequest : Magensa.PPSCRAv2.Services.BasicTransactionRequestInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private string ChallengeField;
        
        private string DeviceTypeField;
        
        private string KSNField;
        
        private string WhiteListTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Challenge
        {
            get
            {
                return this.ChallengeField;
            }
            set
            {
                this.ChallengeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string WhiteListType
        {
            get
            {
                return this.WhiteListTypeField;
            }
            set
            {
                this.WhiteListTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetKeyListRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetKeyListRequest : Magensa.PPSCRAv2.Services.BasicTransactionRequestInfo
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceConfigCommand", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class DeviceConfigCommand : object
    {
        
        private int CommandIdField;
        
        private int ConfigDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommandId
        {
            get
            {
                return this.CommandIdField;
            }
            set
            {
                this.CommandIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConfigData
        {
            get
            {
                return this.ConfigDataField;
            }
            set
            {
                this.ConfigDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasicTransactionResponseInfo", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.PPSCRAv2.Services.GetPPKeyLoadCommandResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.PPSCRAv2.Services.GetAmkKeyLoadCommandResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.PPSCRAv2.Services.GetCertLoadCommandResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.PPSCRAv2.Services.GetLoadConfigCommandResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.PPSCRAv2.Services.GetCommandListByDeviceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.PPSCRAv2.Services.GetDeviceAuthCommandResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.PPSCRAv2.Services.GetPreActivateCommandResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.PPSCRAv2.Services.GetEnableSREDCommandResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.PPSCRAv2.Services.GetKeyListResponse))]
    public partial class BasicTransactionResponseInfo : object
    {
        
        private string CustomerTransactionIdField;
        
        private string MagTranIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionId
        {
            get
            {
                return this.CustomerTransactionIdField;
            }
            set
            {
                this.CustomerTransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagTranId
        {
            get
            {
                return this.MagTranIdField;
            }
            set
            {
                this.MagTranIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPPKeyLoadCommandResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetPPKeyLoadCommandResponse : Magensa.PPSCRAv2.Services.BasicTransactionResponseInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputDataField;
        
        private string BaseKCVField;
        
        private Magensa.PPSCRAv2.Services.Command CommandField;
        
        private string DukptKCVField;
        
        private string KeyPrefixField;
        
        private string KeyTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputData
        {
            get
            {
                return this.AdditionalOutputDataField;
            }
            set
            {
                this.AdditionalOutputDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaseKCV
        {
            get
            {
                return this.BaseKCVField;
            }
            set
            {
                this.BaseKCVField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.PPSCRAv2.Services.Command Command
        {
            get
            {
                return this.CommandField;
            }
            set
            {
                this.CommandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DukptKCV
        {
            get
            {
                return this.DukptKCVField;
            }
            set
            {
                this.DukptKCVField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyPrefix
        {
            get
            {
                return this.KeyPrefixField;
            }
            set
            {
                this.KeyPrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyType
        {
            get
            {
                return this.KeyTypeField;
            }
            set
            {
                this.KeyTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAmkKeyLoadCommandResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetAmkKeyLoadCommandResponse : Magensa.PPSCRAv2.Services.BasicTransactionResponseInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputDataField;
        
        private Magensa.PPSCRAv2.Services.Command CommandField;
        
        private string KCVField;
        
        private string KeyTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputData
        {
            get
            {
                return this.AdditionalOutputDataField;
            }
            set
            {
                this.AdditionalOutputDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.PPSCRAv2.Services.Command Command
        {
            get
            {
                return this.CommandField;
            }
            set
            {
                this.CommandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KCV
        {
            get
            {
                return this.KCVField;
            }
            set
            {
                this.KCVField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyType
        {
            get
            {
                return this.KeyTypeField;
            }
            set
            {
                this.KeyTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCertLoadCommandResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetCertLoadCommandResponse : Magensa.PPSCRAv2.Services.BasicTransactionResponseInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputDataField;
        
        private Magensa.PPSCRAv2.Services.Command CommandField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputData
        {
            get
            {
                return this.AdditionalOutputDataField;
            }
            set
            {
                this.AdditionalOutputDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.PPSCRAv2.Services.Command Command
        {
            get
            {
                return this.CommandField;
            }
            set
            {
                this.CommandField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLoadConfigCommandResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetLoadConfigCommandResponse : Magensa.PPSCRAv2.Services.BasicTransactionResponseInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputDataField;
        
        private Magensa.PPSCRAv2.Services.Command CommandField;
        
        private string TargetConfigField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputData
        {
            get
            {
                return this.AdditionalOutputDataField;
            }
            set
            {
                this.AdditionalOutputDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.PPSCRAv2.Services.Command Command
        {
            get
            {
                return this.CommandField;
            }
            set
            {
                this.CommandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetConfig
        {
            get
            {
                return this.TargetConfigField;
            }
            set
            {
                this.TargetConfigField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCommandListByDeviceResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetCommandListByDeviceResponse : Magensa.PPSCRAv2.Services.BasicTransactionResponseInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputDataField;
        
        private Magensa.PPSCRAv2.Services.Command[] CommandsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputData
        {
            get
            {
                return this.AdditionalOutputDataField;
            }
            set
            {
                this.AdditionalOutputDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.PPSCRAv2.Services.Command[] Commands
        {
            get
            {
                return this.CommandsField;
            }
            set
            {
                this.CommandsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeviceAuthCommandResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetDeviceAuthCommandResponse : Magensa.PPSCRAv2.Services.BasicTransactionResponseInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputDataField;
        
        private Magensa.PPSCRAv2.Services.Command CommandField;
        
        private string KCVField;
        
        private string KeyTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputData
        {
            get
            {
                return this.AdditionalOutputDataField;
            }
            set
            {
                this.AdditionalOutputDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.PPSCRAv2.Services.Command Command
        {
            get
            {
                return this.CommandField;
            }
            set
            {
                this.CommandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KCV
        {
            get
            {
                return this.KCVField;
            }
            set
            {
                this.KCVField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyType
        {
            get
            {
                return this.KeyTypeField;
            }
            set
            {
                this.KeyTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPreActivateCommandResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetPreActivateCommandResponse : Magensa.PPSCRAv2.Services.BasicTransactionResponseInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputDataField;
        
        private Magensa.PPSCRAv2.Services.Command CommandField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputData
        {
            get
            {
                return this.AdditionalOutputDataField;
            }
            set
            {
                this.AdditionalOutputDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.PPSCRAv2.Services.Command Command
        {
            get
            {
                return this.CommandField;
            }
            set
            {
                this.CommandField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetEnableSREDCommandResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetEnableSREDCommandResponse : Magensa.PPSCRAv2.Services.BasicTransactionResponseInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputDataField;
        
        private Magensa.PPSCRAv2.Services.Command CommandField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputData
        {
            get
            {
                return this.AdditionalOutputDataField;
            }
            set
            {
                this.AdditionalOutputDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.PPSCRAv2.Services.Command Command
        {
            get
            {
                return this.CommandField;
            }
            set
            {
                this.CommandField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetKeyListResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetKeyListResponse : Magensa.PPSCRAv2.Services.BasicTransactionResponseInfo
    {
        
        private Magensa.PPSCRAv2.Services.Key[] KeysField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.PPSCRAv2.Services.Key[] Keys
        {
            get
            {
                return this.KeysField;
            }
            set
            {
                this.KeysField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Key", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class Key : object
    {
        
        private string DescriptionField;
        
        private int IDField;
        
        private string KSIField;
        
        private string KeyNameField;
        
        private string KeySlotNamePrefixField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KSI
        {
            get
            {
                return this.KSIField;
            }
            set
            {
                this.KSIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyName
        {
            get
            {
                return this.KeyNameField;
            }
            set
            {
                this.KeyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeySlotNamePrefix
        {
            get
            {
                return this.KeySlotNamePrefixField;
            }
            set
            {
                this.KeySlotNamePrefixField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Command", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class Command : object
    {
        
        private int CommandTypeField;
        
        private string DescriptionField;
        
        private string ExecutionTypeEnumField;
        
        private int IDField;
        
        private string NameField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommandType
        {
            get
            {
                return this.CommandTypeField;
            }
            set
            {
                this.CommandTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExecutionTypeEnum
        {
            get
            {
                return this.ExecutionTypeEnumField;
            }
            set
            {
                this.ExecutionTypeEnumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.magensa.net/RemoteServices/v2/", ConfigurationName="Magensa.PPSCRAv2.Services.IPPSCRAv2")]
    public interface IPPSCRAv2
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetKeyList", ReplyAction="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetKeyListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetKeyListFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Magensa.PPSCRAv2.Services.GetKeyListResponse GetKeyList(Magensa.PPSCRAv2.Services.GetKeyListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetKeyList", ReplyAction="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetKeyListResponse")]
        System.Threading.Tasks.Task<Magensa.PPSCRAv2.Services.GetKeyListResponse> GetKeyListAsync(Magensa.PPSCRAv2.Services.GetKeyListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetKeyLoadCommand", ReplyAction="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetKeyLoadCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetKeyLoadCommandFaultExceptio" +
            "nFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Magensa.PPSCRAv2.Services.GetPPKeyLoadCommandResponse GetKeyLoadCommand(Magensa.PPSCRAv2.Services.GetPPKeyLoadCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetKeyLoadCommand", ReplyAction="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetKeyLoadCommandResponse")]
        System.Threading.Tasks.Task<Magensa.PPSCRAv2.Services.GetPPKeyLoadCommandResponse> GetKeyLoadCommandAsync(Magensa.PPSCRAv2.Services.GetPPKeyLoadCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetAmkKeyLoadCommand", ReplyAction="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetAmkKeyLoadCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetAmkKeyLoadCommandFaultExcep" +
            "tionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Magensa.PPSCRAv2.Services.GetAmkKeyLoadCommandResponse GetAmkKeyLoadCommand(Magensa.PPSCRAv2.Services.GetAmkKeyLoadCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetAmkKeyLoadCommand", ReplyAction="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetAmkKeyLoadCommandResponse")]
        System.Threading.Tasks.Task<Magensa.PPSCRAv2.Services.GetAmkKeyLoadCommandResponse> GetAmkKeyLoadCommandAsync(Magensa.PPSCRAv2.Services.GetAmkKeyLoadCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetCertLoadCommand", ReplyAction="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetCertLoadCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetCertLoadCommandFaultExcepti" +
            "onFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Magensa.PPSCRAv2.Services.GetCertLoadCommandResponse GetCertLoadCommand(Magensa.PPSCRAv2.Services.GetCertLoadCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetCertLoadCommand", ReplyAction="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetCertLoadCommandResponse")]
        System.Threading.Tasks.Task<Magensa.PPSCRAv2.Services.GetCertLoadCommandResponse> GetCertLoadCommandAsync(Magensa.PPSCRAv2.Services.GetCertLoadCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetLoadConfigCommand", ReplyAction="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetLoadConfigCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetLoadConfigCommandFaultExcep" +
            "tionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Magensa.PPSCRAv2.Services.GetLoadConfigCommandResponse GetLoadConfigCommand(Magensa.PPSCRAv2.Services.GetLoadConfigCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetLoadConfigCommand", ReplyAction="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetLoadConfigCommandResponse")]
        System.Threading.Tasks.Task<Magensa.PPSCRAv2.Services.GetLoadConfigCommandResponse> GetLoadConfigCommandAsync(Magensa.PPSCRAv2.Services.GetLoadConfigCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetCommandListByDevice", ReplyAction="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetCommandListByDeviceResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetCommandListByDeviceFaultExc" +
            "eptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Magensa.PPSCRAv2.Services.GetCommandListByDeviceResponse GetCommandListByDevice(Magensa.PPSCRAv2.Services.GetCommandListByDeviceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetCommandListByDevice", ReplyAction="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetCommandListByDeviceResponse" +
            "")]
        System.Threading.Tasks.Task<Magensa.PPSCRAv2.Services.GetCommandListByDeviceResponse> GetCommandListByDeviceAsync(Magensa.PPSCRAv2.Services.GetCommandListByDeviceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetDeviceAuthCommand", ReplyAction="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetDeviceAuthCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetDeviceAuthCommandFaultExcep" +
            "tionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Magensa.PPSCRAv2.Services.GetDeviceAuthCommandResponse GetDeviceAuthCommand(Magensa.PPSCRAv2.Services.GetDeviceAuthCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetDeviceAuthCommand", ReplyAction="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetDeviceAuthCommandResponse")]
        System.Threading.Tasks.Task<Magensa.PPSCRAv2.Services.GetDeviceAuthCommandResponse> GetDeviceAuthCommandAsync(Magensa.PPSCRAv2.Services.GetDeviceAuthCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetPreActivateCommand", ReplyAction="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetPreActivateCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetPreActivateCommandFaultExce" +
            "ptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Magensa.PPSCRAv2.Services.GetPreActivateCommandResponse GetPreActivateCommand(Magensa.PPSCRAv2.Services.GetPreActivateCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetPreActivateCommand", ReplyAction="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetPreActivateCommandResponse")]
        System.Threading.Tasks.Task<Magensa.PPSCRAv2.Services.GetPreActivateCommandResponse> GetPreActivateCommandAsync(Magensa.PPSCRAv2.Services.GetPreActivateCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetEnableSREDCommand", ReplyAction="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetEnableSREDCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetEnableSREDCommandFaultExcep" +
            "tionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Magensa.PPSCRAv2.Services.GetEnableSREDCommandResponse GetEnableSREDCommand(Magensa.PPSCRAv2.Services.GetEnableSREDCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetEnableSREDCommand", ReplyAction="http://www.magensa.net/RemoteServices/v2/IPPSCRAv2/GetEnableSREDCommandResponse")]
        System.Threading.Tasks.Task<Magensa.PPSCRAv2.Services.GetEnableSREDCommandResponse> GetEnableSREDCommandAsync(Magensa.PPSCRAv2.Services.GetEnableSREDCommandRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IPPSCRAv2Channel : Magensa.PPSCRAv2.Services.IPPSCRAv2, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PPSCRAv2Client : System.ServiceModel.ClientBase<Magensa.PPSCRAv2.Services.IPPSCRAv2>, Magensa.PPSCRAv2.Services.IPPSCRAv2
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PPSCRAv2Client() : 
                base(PPSCRAv2Client.GetDefaultBinding(), PPSCRAv2Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpsBinding_IPPSCRAv2.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PPSCRAv2Client(EndpointConfiguration endpointConfiguration) : 
                base(PPSCRAv2Client.GetBindingForEndpoint(endpointConfiguration), PPSCRAv2Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PPSCRAv2Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PPSCRAv2Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PPSCRAv2Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PPSCRAv2Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PPSCRAv2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Magensa.PPSCRAv2.Services.GetKeyListResponse GetKeyList(Magensa.PPSCRAv2.Services.GetKeyListRequest request)
        {
            return base.Channel.GetKeyList(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.PPSCRAv2.Services.GetKeyListResponse> GetKeyListAsync(Magensa.PPSCRAv2.Services.GetKeyListRequest request)
        {
            return base.Channel.GetKeyListAsync(request);
        }
        
        public Magensa.PPSCRAv2.Services.GetPPKeyLoadCommandResponse GetKeyLoadCommand(Magensa.PPSCRAv2.Services.GetPPKeyLoadCommandRequest request)
        {
            return base.Channel.GetKeyLoadCommand(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.PPSCRAv2.Services.GetPPKeyLoadCommandResponse> GetKeyLoadCommandAsync(Magensa.PPSCRAv2.Services.GetPPKeyLoadCommandRequest request)
        {
            return base.Channel.GetKeyLoadCommandAsync(request);
        }
        
        public Magensa.PPSCRAv2.Services.GetAmkKeyLoadCommandResponse GetAmkKeyLoadCommand(Magensa.PPSCRAv2.Services.GetAmkKeyLoadCommandRequest request)
        {
            return base.Channel.GetAmkKeyLoadCommand(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.PPSCRAv2.Services.GetAmkKeyLoadCommandResponse> GetAmkKeyLoadCommandAsync(Magensa.PPSCRAv2.Services.GetAmkKeyLoadCommandRequest request)
        {
            return base.Channel.GetAmkKeyLoadCommandAsync(request);
        }
        
        public Magensa.PPSCRAv2.Services.GetCertLoadCommandResponse GetCertLoadCommand(Magensa.PPSCRAv2.Services.GetCertLoadCommandRequest request)
        {
            return base.Channel.GetCertLoadCommand(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.PPSCRAv2.Services.GetCertLoadCommandResponse> GetCertLoadCommandAsync(Magensa.PPSCRAv2.Services.GetCertLoadCommandRequest request)
        {
            return base.Channel.GetCertLoadCommandAsync(request);
        }
        
        public Magensa.PPSCRAv2.Services.GetLoadConfigCommandResponse GetLoadConfigCommand(Magensa.PPSCRAv2.Services.GetLoadConfigCommandRequest request)
        {
            return base.Channel.GetLoadConfigCommand(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.PPSCRAv2.Services.GetLoadConfigCommandResponse> GetLoadConfigCommandAsync(Magensa.PPSCRAv2.Services.GetLoadConfigCommandRequest request)
        {
            return base.Channel.GetLoadConfigCommandAsync(request);
        }
        
        public Magensa.PPSCRAv2.Services.GetCommandListByDeviceResponse GetCommandListByDevice(Magensa.PPSCRAv2.Services.GetCommandListByDeviceRequest request)
        {
            return base.Channel.GetCommandListByDevice(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.PPSCRAv2.Services.GetCommandListByDeviceResponse> GetCommandListByDeviceAsync(Magensa.PPSCRAv2.Services.GetCommandListByDeviceRequest request)
        {
            return base.Channel.GetCommandListByDeviceAsync(request);
        }
        
        public Magensa.PPSCRAv2.Services.GetDeviceAuthCommandResponse GetDeviceAuthCommand(Magensa.PPSCRAv2.Services.GetDeviceAuthCommandRequest request)
        {
            return base.Channel.GetDeviceAuthCommand(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.PPSCRAv2.Services.GetDeviceAuthCommandResponse> GetDeviceAuthCommandAsync(Magensa.PPSCRAv2.Services.GetDeviceAuthCommandRequest request)
        {
            return base.Channel.GetDeviceAuthCommandAsync(request);
        }
        
        public Magensa.PPSCRAv2.Services.GetPreActivateCommandResponse GetPreActivateCommand(Magensa.PPSCRAv2.Services.GetPreActivateCommandRequest request)
        {
            return base.Channel.GetPreActivateCommand(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.PPSCRAv2.Services.GetPreActivateCommandResponse> GetPreActivateCommandAsync(Magensa.PPSCRAv2.Services.GetPreActivateCommandRequest request)
        {
            return base.Channel.GetPreActivateCommandAsync(request);
        }
        
        public Magensa.PPSCRAv2.Services.GetEnableSREDCommandResponse GetEnableSREDCommand(Magensa.PPSCRAv2.Services.GetEnableSREDCommandRequest request)
        {
            return base.Channel.GetEnableSREDCommand(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.PPSCRAv2.Services.GetEnableSREDCommandResponse> GetEnableSREDCommandAsync(Magensa.PPSCRAv2.Services.GetEnableSREDCommandRequest request)
        {
            return base.Channel.GetEnableSREDCommandAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IPPSCRAv2))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IPPSCRAv2))
            {
                return new System.ServiceModel.EndpointAddress("https://devgw.magensa.dev/RemoteServicesV2/PPSCRAv2.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PPSCRAv2Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpsBinding_IPPSCRAv2);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PPSCRAv2Client.GetEndpointAddress(EndpointConfiguration.BasicHttpsBinding_IPPSCRAv2);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpsBinding_IPPSCRAv2,
        }
    }
}
