//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magensa.SCRAv2.Services
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasicTransactionRequestInfo", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.SCRAv2.Services.GetCommandListRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.SCRAv2.Services.GetFirmwareListRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.SCRAv2.Services.GetCommandByKSNRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.SCRAv2.Services.GetCommandByMUTRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.SCRAv2.Services.GetFirmwareByMUTRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.SCRAv2.Services.GetKeyLoadCommandRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.SCRAv2.Services.GetFirmwareCommandsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.SCRAv2.Services.GetKeyListRequest))]
    public partial class BasicTransactionRequestInfo : object
    {
        
        private Magensa.SCRAv2.Services.Authentication AuthenticationField;
        
        private string BillingLabelField;
        
        private string CustomerTransactionIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.SCRAv2.Services.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingLabel
        {
            get
            {
                return this.BillingLabelField;
            }
            set
            {
                this.BillingLabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authentication", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class Authentication : object
    {
        
        private string CustomerCodeField;
        
        private string PasswordField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomerCode
        {
            get
            {
                return this.CustomerCodeField;
            }
            set
            {
                this.CustomerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCommandListRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetCommandListRequest : Magensa.SCRAv2.Services.BasicTransactionRequestInfo
    {
        
        private string ExecutionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ExecutionType
        {
            get
            {
                return this.ExecutionTypeField;
            }
            set
            {
                this.ExecutionTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFirmwareListRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetFirmwareListRequest : Magensa.SCRAv2.Services.BasicTransactionRequestInfo
    {
        
        private string FirmwareTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirmwareType
        {
            get
            {
                return this.FirmwareTypeField;
            }
            set
            {
                this.FirmwareTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCommandByKSNRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetCommandByKSNRequest : Magensa.SCRAv2.Services.BasicTransactionRequestInfo
    {
        
        private int CommandIDField;
        
        private string KSNField;
        
        private int KeyIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CommandID
        {
            get
            {
                return this.CommandIDField;
            }
            set
            {
                this.CommandIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int KeyID
        {
            get
            {
                return this.KeyIDField;
            }
            set
            {
                this.KeyIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCommandByMUTRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetCommandByMUTRequest : Magensa.SCRAv2.Services.BasicTransactionRequestInfo
    {
        
        private int CommandIDField;
        
        private string KSNField;
        
        private string UpdateTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CommandID
        {
            get
            {
                return this.CommandIDField;
            }
            set
            {
                this.CommandIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UpdateToken
        {
            get
            {
                return this.UpdateTokenField;
            }
            set
            {
                this.UpdateTokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFirmwareByMUTRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetFirmwareByMUTRequest : Magensa.SCRAv2.Services.BasicTransactionRequestInfo
    {
        
        private int FirmwareIDField;
        
        private string KSNField;
        
        private string UpdateTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int FirmwareID
        {
            get
            {
                return this.FirmwareIDField;
            }
            set
            {
                this.FirmwareIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UpdateToken
        {
            get
            {
                return this.UpdateTokenField;
            }
            set
            {
                this.UpdateTokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetKeyLoadCommandRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetKeyLoadCommandRequest : Magensa.SCRAv2.Services.BasicTransactionRequestInfo
    {
        
        private string KSNField;
        
        private int KeyIDField;
        
        private string UpdateTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int KeyID
        {
            get
            {
                return this.KeyIDField;
            }
            set
            {
                this.KeyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UpdateToken
        {
            get
            {
                return this.UpdateTokenField;
            }
            set
            {
                this.UpdateTokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFirmwareCommandsRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetFirmwareCommandsRequest : Magensa.SCRAv2.Services.BasicTransactionRequestInfo
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private string DeviceTypeField;
        
        private byte[] FirmwareField;
        
        private string KSNField;
        
        private int KeyIDField;
        
        private string SerialNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] Firmware
        {
            get
            {
                return this.FirmwareField;
            }
            set
            {
                this.FirmwareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int KeyID
        {
            get
            {
                return this.KeyIDField;
            }
            set
            {
                this.KeyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber
        {
            get
            {
                return this.SerialNumberField;
            }
            set
            {
                this.SerialNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetKeyListRequest", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetKeyListRequest : Magensa.SCRAv2.Services.BasicTransactionRequestInfo
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasicTransactionResponseInfo", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.SCRAv2.Services.GetCommandListResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.SCRAv2.Services.GetFirmwareListResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.SCRAv2.Services.GetCommandByKSNResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.SCRAv2.Services.GetCommandByMUTResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.SCRAv2.Services.GetFirmwareByMUTResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.SCRAv2.Services.GetKeyLoadCommandResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.SCRAv2.Services.GetFirmwareCommandsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.SCRAv2.Services.GetKeyListResponse))]
    public partial class BasicTransactionResponseInfo : object
    {
        
        private string CustomerTransactionIdField;
        
        private string MagTranIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionId
        {
            get
            {
                return this.CustomerTransactionIdField;
            }
            set
            {
                this.CustomerTransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagTranId
        {
            get
            {
                return this.MagTranIdField;
            }
            set
            {
                this.MagTranIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCommandListResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetCommandListResponse : Magensa.SCRAv2.Services.BasicTransactionResponseInfo
    {
        
        private Magensa.SCRAv2.Services.Command[] CommandsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.SCRAv2.Services.Command[] Commands
        {
            get
            {
                return this.CommandsField;
            }
            set
            {
                this.CommandsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFirmwareListResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetFirmwareListResponse : Magensa.SCRAv2.Services.BasicTransactionResponseInfo
    {
        
        private Magensa.SCRAv2.Services.Firmware[] FirmwaresField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.SCRAv2.Services.Firmware[] Firmwares
        {
            get
            {
                return this.FirmwaresField;
            }
            set
            {
                this.FirmwaresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCommandByKSNResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetCommandByKSNResponse : Magensa.SCRAv2.Services.BasicTransactionResponseInfo
    {
        
        private Magensa.SCRAv2.Services.Command CommandField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.SCRAv2.Services.Command Command
        {
            get
            {
                return this.CommandField;
            }
            set
            {
                this.CommandField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCommandByMUTResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetCommandByMUTResponse : Magensa.SCRAv2.Services.BasicTransactionResponseInfo
    {
        
        private Magensa.SCRAv2.Services.Command CommandField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.SCRAv2.Services.Command Command
        {
            get
            {
                return this.CommandField;
            }
            set
            {
                this.CommandField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFirmwareByMUTResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetFirmwareByMUTResponse : Magensa.SCRAv2.Services.BasicTransactionResponseInfo
    {
        
        private Magensa.SCRAv2.Services.Firmware FirmwareField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.SCRAv2.Services.Firmware Firmware
        {
            get
            {
                return this.FirmwareField;
            }
            set
            {
                this.FirmwareField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetKeyLoadCommandResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetKeyLoadCommandResponse : Magensa.SCRAv2.Services.BasicTransactionResponseInfo
    {
        
        private Magensa.SCRAv2.Services.Command[] CommandsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.SCRAv2.Services.Command[] Commands
        {
            get
            {
                return this.CommandsField;
            }
            set
            {
                this.CommandsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFirmwareCommandsResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetFirmwareCommandsResponse : Magensa.SCRAv2.Services.BasicTransactionResponseInfo
    {
        
        private string[] CommandsField;
        
        private Magensa.SCRAv2.Services.FirmwareCommand[] PostloadCommandsField;
        
        private Magensa.SCRAv2.Services.FirmwareCommand[] PreloadCommandsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Commands
        {
            get
            {
                return this.CommandsField;
            }
            set
            {
                this.CommandsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.SCRAv2.Services.FirmwareCommand[] PostloadCommands
        {
            get
            {
                return this.PostloadCommandsField;
            }
            set
            {
                this.PostloadCommandsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.SCRAv2.Services.FirmwareCommand[] PreloadCommands
        {
            get
            {
                return this.PreloadCommandsField;
            }
            set
            {
                this.PreloadCommandsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetKeyListResponse", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class GetKeyListResponse : Magensa.SCRAv2.Services.BasicTransactionResponseInfo
    {
        
        private Magensa.SCRAv2.Services.Key[] KeysField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.SCRAv2.Services.Key[] Keys
        {
            get
            {
                return this.KeysField;
            }
            set
            {
                this.KeysField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Key", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class Key : object
    {
        
        private string DescriptionField;
        
        private int IDField;
        
        private string KSIField;
        
        private string KeyNameField;
        
        private string KeySlotNamePrefixField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KSI
        {
            get
            {
                return this.KSIField;
            }
            set
            {
                this.KSIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyName
        {
            get
            {
                return this.KeyNameField;
            }
            set
            {
                this.KeyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeySlotNamePrefix
        {
            get
            {
                return this.KeySlotNamePrefixField;
            }
            set
            {
                this.KeySlotNamePrefixField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Command", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class Command : object
    {
        
        private int CommandTypeField;
        
        private string DescriptionField;
        
        private string ExecutionTypeEnumField;
        
        private int IDField;
        
        private string NameField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommandType
        {
            get
            {
                return this.CommandTypeField;
            }
            set
            {
                this.CommandTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExecutionTypeEnum
        {
            get
            {
                return this.ExecutionTypeEnumField;
            }
            set
            {
                this.ExecutionTypeEnumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Firmware", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class Firmware : object
    {
        
        private string DateCreatedField;
        
        private string DateModifiedField;
        
        private string DescriptionField;
        
        private string FileField;
        
        private int IDField;
        
        private string NameField;
        
        private string PartNumberField;
        
        private Magensa.SCRAv2.Services.FirmwareCommand[] PostloadCommandsField;
        
        private Magensa.SCRAv2.Services.FirmwareCommand[] PreloadCommandsField;
        
        private byte TargetIDField;
        
        private string TypeField;
        
        private string VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateCreated
        {
            get
            {
                return this.DateCreatedField;
            }
            set
            {
                this.DateCreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateModified
        {
            get
            {
                return this.DateModifiedField;
            }
            set
            {
                this.DateModifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string File
        {
            get
            {
                return this.FileField;
            }
            set
            {
                this.FileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartNumber
        {
            get
            {
                return this.PartNumberField;
            }
            set
            {
                this.PartNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.SCRAv2.Services.FirmwareCommand[] PostloadCommands
        {
            get
            {
                return this.PostloadCommandsField;
            }
            set
            {
                this.PostloadCommandsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.SCRAv2.Services.FirmwareCommand[] PreloadCommands
        {
            get
            {
                return this.PreloadCommandsField;
            }
            set
            {
                this.PreloadCommandsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte TargetID
        {
            get
            {
                return this.TargetIDField;
            }
            set
            {
                this.TargetIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FirmwareCommand", Namespace="http://schemas.datacontract.org/2004/07/RemoteServicesv2.Core")]
    public partial class FirmwareCommand : object
    {
        
        private string OperationField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operation
        {
            get
            {
                return this.OperationField;
            }
            set
            {
                this.OperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.magensa.net/RemoteServices/v2/", ConfigurationName="Magensa.SCRAv2.Services.ISCRAv2")]
    public interface ISCRAv2
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetKeyList", ReplyAction="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetKeyListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetKeyListFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Magensa.SCRAv2.Services.GetKeyListResponse GetKeyList(Magensa.SCRAv2.Services.GetKeyListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetKeyList", ReplyAction="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetKeyListResponse")]
        System.Threading.Tasks.Task<Magensa.SCRAv2.Services.GetKeyListResponse> GetKeyListAsync(Magensa.SCRAv2.Services.GetKeyListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetCommandList", ReplyAction="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetCommandListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetCommandListFaultExceptionFaul" +
            "t", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Magensa.SCRAv2.Services.GetCommandListResponse GetCommandList(Magensa.SCRAv2.Services.GetCommandListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetCommandList", ReplyAction="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetCommandListResponse")]
        System.Threading.Tasks.Task<Magensa.SCRAv2.Services.GetCommandListResponse> GetCommandListAsync(Magensa.SCRAv2.Services.GetCommandListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetFirmwareList", ReplyAction="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetFirmwareListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetFirmwareListFaultExceptionFau" +
            "lt", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Magensa.SCRAv2.Services.GetFirmwareListResponse GetFirmwareList(Magensa.SCRAv2.Services.GetFirmwareListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetFirmwareList", ReplyAction="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetFirmwareListResponse")]
        System.Threading.Tasks.Task<Magensa.SCRAv2.Services.GetFirmwareListResponse> GetFirmwareListAsync(Magensa.SCRAv2.Services.GetFirmwareListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetCommandByKSN", ReplyAction="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetCommandByKSNResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetCommandByKSNFaultExceptionFau" +
            "lt", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Magensa.SCRAv2.Services.GetCommandByKSNResponse GetCommandByKSN(Magensa.SCRAv2.Services.GetCommandByKSNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetCommandByKSN", ReplyAction="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetCommandByKSNResponse")]
        System.Threading.Tasks.Task<Magensa.SCRAv2.Services.GetCommandByKSNResponse> GetCommandByKSNAsync(Magensa.SCRAv2.Services.GetCommandByKSNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetCommandByMUT", ReplyAction="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetCommandByMUTResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetCommandByMUTFaultExceptionFau" +
            "lt", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Magensa.SCRAv2.Services.GetCommandByMUTResponse GetCommandByMUT(Magensa.SCRAv2.Services.GetCommandByMUTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetCommandByMUT", ReplyAction="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetCommandByMUTResponse")]
        System.Threading.Tasks.Task<Magensa.SCRAv2.Services.GetCommandByMUTResponse> GetCommandByMUTAsync(Magensa.SCRAv2.Services.GetCommandByMUTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetFirmwareByMUT", ReplyAction="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetFirmwareByMUTResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetFirmwareByMUTFaultExceptionFa" +
            "ult", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Magensa.SCRAv2.Services.GetFirmwareByMUTResponse GetFirmwareByMUT(Magensa.SCRAv2.Services.GetFirmwareByMUTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetFirmwareByMUT", ReplyAction="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetFirmwareByMUTResponse")]
        System.Threading.Tasks.Task<Magensa.SCRAv2.Services.GetFirmwareByMUTResponse> GetFirmwareByMUTAsync(Magensa.SCRAv2.Services.GetFirmwareByMUTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetKeyLoadCommand", ReplyAction="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetKeyLoadCommandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetKeyLoadCommandFaultExceptionF" +
            "ault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Magensa.SCRAv2.Services.GetKeyLoadCommandResponse GetKeyLoadCommand(Magensa.SCRAv2.Services.GetKeyLoadCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetKeyLoadCommand", ReplyAction="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetKeyLoadCommandResponse")]
        System.Threading.Tasks.Task<Magensa.SCRAv2.Services.GetKeyLoadCommandResponse> GetKeyLoadCommandAsync(Magensa.SCRAv2.Services.GetKeyLoadCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetFirmwareCommands", ReplyAction="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetFirmwareCommandsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetFirmwareCommandsFaultExceptio" +
            "nFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Magensa.SCRAv2.Services.GetFirmwareCommandsResponse GetFirmwareCommands(Magensa.SCRAv2.Services.GetFirmwareCommandsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetFirmwareCommands", ReplyAction="http://www.magensa.net/RemoteServices/v2/ISCRAv2/GetFirmwareCommandsResponse")]
        System.Threading.Tasks.Task<Magensa.SCRAv2.Services.GetFirmwareCommandsResponse> GetFirmwareCommandsAsync(Magensa.SCRAv2.Services.GetFirmwareCommandsRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ISCRAv2Channel : Magensa.SCRAv2.Services.ISCRAv2, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SCRAv2Client : System.ServiceModel.ClientBase<Magensa.SCRAv2.Services.ISCRAv2>, Magensa.SCRAv2.Services.ISCRAv2
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SCRAv2Client() : 
                base(SCRAv2Client.GetDefaultBinding(), SCRAv2Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpsBinding_ISCRAv2.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SCRAv2Client(EndpointConfiguration endpointConfiguration) : 
                base(SCRAv2Client.GetBindingForEndpoint(endpointConfiguration), SCRAv2Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SCRAv2Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SCRAv2Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SCRAv2Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SCRAv2Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SCRAv2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Magensa.SCRAv2.Services.GetKeyListResponse GetKeyList(Magensa.SCRAv2.Services.GetKeyListRequest request)
        {
            return base.Channel.GetKeyList(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.SCRAv2.Services.GetKeyListResponse> GetKeyListAsync(Magensa.SCRAv2.Services.GetKeyListRequest request)
        {
            return base.Channel.GetKeyListAsync(request);
        }
        
        public Magensa.SCRAv2.Services.GetCommandListResponse GetCommandList(Magensa.SCRAv2.Services.GetCommandListRequest request)
        {
            return base.Channel.GetCommandList(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.SCRAv2.Services.GetCommandListResponse> GetCommandListAsync(Magensa.SCRAv2.Services.GetCommandListRequest request)
        {
            return base.Channel.GetCommandListAsync(request);
        }
        
        public Magensa.SCRAv2.Services.GetFirmwareListResponse GetFirmwareList(Magensa.SCRAv2.Services.GetFirmwareListRequest request)
        {
            return base.Channel.GetFirmwareList(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.SCRAv2.Services.GetFirmwareListResponse> GetFirmwareListAsync(Magensa.SCRAv2.Services.GetFirmwareListRequest request)
        {
            return base.Channel.GetFirmwareListAsync(request);
        }
        
        public Magensa.SCRAv2.Services.GetCommandByKSNResponse GetCommandByKSN(Magensa.SCRAv2.Services.GetCommandByKSNRequest request)
        {
            return base.Channel.GetCommandByKSN(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.SCRAv2.Services.GetCommandByKSNResponse> GetCommandByKSNAsync(Magensa.SCRAv2.Services.GetCommandByKSNRequest request)
        {
            return base.Channel.GetCommandByKSNAsync(request);
        }
        
        public Magensa.SCRAv2.Services.GetCommandByMUTResponse GetCommandByMUT(Magensa.SCRAv2.Services.GetCommandByMUTRequest request)
        {
            return base.Channel.GetCommandByMUT(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.SCRAv2.Services.GetCommandByMUTResponse> GetCommandByMUTAsync(Magensa.SCRAv2.Services.GetCommandByMUTRequest request)
        {
            return base.Channel.GetCommandByMUTAsync(request);
        }
        
        public Magensa.SCRAv2.Services.GetFirmwareByMUTResponse GetFirmwareByMUT(Magensa.SCRAv2.Services.GetFirmwareByMUTRequest request)
        {
            return base.Channel.GetFirmwareByMUT(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.SCRAv2.Services.GetFirmwareByMUTResponse> GetFirmwareByMUTAsync(Magensa.SCRAv2.Services.GetFirmwareByMUTRequest request)
        {
            return base.Channel.GetFirmwareByMUTAsync(request);
        }
        
        public Magensa.SCRAv2.Services.GetKeyLoadCommandResponse GetKeyLoadCommand(Magensa.SCRAv2.Services.GetKeyLoadCommandRequest request)
        {
            return base.Channel.GetKeyLoadCommand(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.SCRAv2.Services.GetKeyLoadCommandResponse> GetKeyLoadCommandAsync(Magensa.SCRAv2.Services.GetKeyLoadCommandRequest request)
        {
            return base.Channel.GetKeyLoadCommandAsync(request);
        }
        
        public Magensa.SCRAv2.Services.GetFirmwareCommandsResponse GetFirmwareCommands(Magensa.SCRAv2.Services.GetFirmwareCommandsRequest request)
        {
            return base.Channel.GetFirmwareCommands(request);
        }
        
        public System.Threading.Tasks.Task<Magensa.SCRAv2.Services.GetFirmwareCommandsResponse> GetFirmwareCommandsAsync(Magensa.SCRAv2.Services.GetFirmwareCommandsRequest request)
        {
            return base.Channel.GetFirmwareCommandsAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_ISCRAv2))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_ISCRAv2))
            {
                return new System.ServiceModel.EndpointAddress("https://devgw.magensa.dev/RemoteServicesV2/SCRAv2.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SCRAv2Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpsBinding_ISCRAv2);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SCRAv2Client.GetEndpointAddress(EndpointConfiguration.BasicHttpsBinding_ISCRAv2);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpsBinding_ISCRAv2,
        }
    }
}
